{
 "title": "_ Node App - Dashboard Copy",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Node-App Pod Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(kube_pod_info{namespace=\"sre-challenge\", pod=~\"node-app.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_response_time_seconds_sum[1m]) / rate(http_response_time_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"sre-challenge\", pod=~\"node-app.*\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Requests per Minute",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 11, "y": 9 },
   "targets": [
    {
     "expr": "rate(http_response_time_seconds_count[1m]) * 60",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}