---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  namespace: sre-challenge
  labels:
    app: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      nodeSelector:
        sre-chaos-poc/node-pool: "service"
      containers:
        - name: node-app
          image: sre-chaos-poc:latest
          imagePullPolicy: Never   # useful when loading images into kind cluster... laoding the image results in an error
          ports:
            - containerPort: 3000
          env:
            - name: REDIS_HOST
              value: "redis-headless.sre-challenge-platform"
            - name: REDIS_PORT
              value: "6379"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
