---
apiVersion: v1
kind: Service
metadata:
  name: node-app
  namespace: sre-challenge
  labels:
    app: node-app
spec:
  selector:
    app: node-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: metrics
      protocol: TCP
      port: 9464
      targetPort: 9464 # Expose metrics port
  type: ClusterIP
